#cloud-config

runcmd:
 - wget -O /tmp/pl-release-jessie.deb -q https://apt.puppetlabs.com/puppetlabs-release-pc1-jessie.deb
 - dpkg -i /tmp/pl-release-jessie.deb
 - apt-get update && apt-get install puppet-agent -y -q
 - /opt/puppetlabs/puppet/bin/gem install ipaddress
 - /opt/puppetlabs/bin/puppet module install puppet-network
 - /opt/puppetlabs/bin/puppet module install duritong-sysctl
 - /opt/puppetlabs/bin/puppet apply /etc/ffhs_rn_puppet.pp

packages:
 - man
 - vim
 - tshark
 - tcpdump
 - wget
 - ifupdown-extra
 - nmap
 - traceroute
 - inetutils-ping

power_state:
 mode: reboot
 message: reboot
 timeout: 30
 condition: True

write_files:
 - path: '/etc/ffhs_rn_puppet.pp'
   content: |
     Network_config {
       ensure      => 'present',
       family      => 'inet',
     }
     #
     network_config { 'eth0':
       method  => 'dhcp',
       onboot  => 'true',
     }
     #
     file { '/etc/network/interfaces.d/eth0':
       ensure => 'absent',
     }
     file { '/etc/network/interfaces.d/eth1':
       ensure => 'absent',
     }
     #
     node "ffhs-r1" {
       sysctl::value { "net.ipv4.ip_forward": value => "1"}
       package { ['quagga', 'quagga-doc']: ensure => installed }
       file { '/etc/quagga/zebra.conf':
         owner => 'quagga',
         group => 'quaggavty',
         mode => '0640',
         content => @(END)
           hostname Router
           password zebra
           enable password zebra
           interface eth1
            ip address 192.168.1.1/24
            ipv6 nd suppress-ra
           interface eth2
            ip address 192.168.100.1/24
            ipv6 nd suppress-ra
           interface eth3
            ip address 192.168.101.1/24
            ipv6 nd suppress-ra
           interface lo
           ip forwarding
           line vty
           | END
       } ~> Service['quagga']
       file { '/etc/quagga/ospfd.conf':
         owner => 'quagga',
         group => 'quaggavty',
         mode  => '0640',
         content => @(END)
           hostname ospfd
           password zebra
           log stdout
           interface eth1
           interface eth2
           interface eth3
           interface lo
           router ospf
             passive-interface eth1
             network 192.168.1.0/24 area 0.0.0.0
             network 192.168.100.0/24 area 0.0.0.0
             network 192.168.101.0/24 area 0.0.0.0
           line vty
           | END
       } ~> Service['quagga']
       file { '/etc/quagga/daemons':
         owner => 'quagga',
         group => 'quagga',
         mode => '0640',
         content => @(END)
           zebra=yes
           bgpd=no
           ospfd=yes
           ospf6d=no
           ripd=no
           ripngd=no
           isisd=no
           babeld=no
           | END
       } ~> Service['quagga']
       service { 'quagga': ensure => 'running', }
     }
     #
     node "ffhs-r2" {
       package { ['quagga', 'quagga-doc']: ensure => installed }
       file { '/etc/quagga/zebra.conf':
         owner => 'quagga',
         group => 'quaggavty',
         mode => '0640',
         content => @(END)
           hostname Router
           password zebra
           enable password zebra
           interface eth1
            ip address 192.168.100.2/24
            ipv6 nd suppress-ra
           interface eth2
            ip address 192.168.102.2/24
            ipv6 nd suppress-ra
           interface eth3
            ip address 192.168.2.2/24
            ipv6 nd suppress-ra
           interface lo
           ip forwarding
           line vty
           | END
       } ~> Service['quagga']
       file { '/etc/quagga/ospfd.conf':
         owner => 'quagga',
         group => 'quaggavty',
         mode  => '0640',
         content => @(END)
           hostname ospfd
           password zebra
           log stdout
           interface eth1
           interface eth2
           interface eth3
           interface lo
           router ospf
             passive-interface eth3
             network 192.168.2.0/24 area 0.0.0.0
             network 192.168.100.0/24 area 0.0.0.0
             network 192.168.102.0/24 area 0.0.0.0
           line vty
           | END
       } ~> Service['quagga']
       file { '/etc/quagga/daemons':
         owner => 'quagga',
         group => 'quagga',
         mode => '0640',
         content => @(END)
           zebra=yes
           bgpd=no
           ospfd=yes
           ospf6d=no
           ripd=no
           ripngd=no
           isisd=no
           babeld=no
           | END
       } ~> Service['quagga']
       service { 'quagga': ensure => 'running', }
     }
     node "ffhs-r3" {
       package { ['quagga', 'quagga-doc']: ensure => installed }
       file { '/etc/quagga/zebra.conf':
         owner => 'quagga',
         group => 'quaggavty',
         mode => '0640',
         content => @(END)
           hostname Router
           password zebra
           enable password zebra
           interface eth1
            ip address 192.168.101.3/24
            ipv6 nd suppress-ra
           interface eth2
            ip address 192.168.102.3/24
            ipv6 nd suppress-ra
           interface eth3
            ip address 192.168.3.3/24
            ipv6 nd suppress-ra
           interface lo
           ip forwarding
           line vty
           | END
       } ~> Service['quagga']
       file { '/etc/quagga/ospfd.conf':
         owner => 'quagga',
         group => 'quaggavty',
         mode  => '0640',
         content => @(END)
           hostname ospfd
           password zebra
           log stdout
           interface eth1
           interface eth2
           interface eth3
           interface lo
           router ospf
             passive-interface eth3
             network 192.168.3.0/24 area 0.0.0.0
             network 192.168.101.0/24 area 0.0.0.0
             network 192.168.102.0/24 area 0.0.0.0
           line vty
           | END
       } ~> Service['quagga']
       file { '/etc/quagga/daemons':
         owner => 'quagga',
         group => 'quagga',
         mode => '0640',
         content => @(END)
           zebra=yes
           bgpd=no
           ospfd=yes
           ospf6d=no
           ripd=no
           ripngd=no
           isisd=no
           babeld=no
           | END
       } ~> Service['quagga']
       service { 'quagga': ensure => 'running', }
     }
     node "ffhs-pc1" {
       # enable some basic security
       sysctl::value { "net.ipv4.conf.all.rp_filter": value => "1"}
       #
       # log when rp_filter blocks packages
       sysctl::value { "net.ipv4.conf.all.log_martians": value => "1"}
       # eth0 = private network mit floating ip
       network_config { 'eth1':
         ipaddress => '192.168.1.101',
         method    => 'static',
         netmask   => '255.255.255.0',
         onboot    => 'true',
         options   => {
           'post-up' => [
             'ip route add 192.168.0.0/16 via 192.168.1.1 dev eth1',
           ],
           'pre-down' => [
             'ip route del 192.168.0.0/16 via 192.168.1.1 dev eth1',
           ],
         },
       }
     }
     node "ffhs-pc2" {
       # enable some basic security
       sysctl::value { "net.ipv4.conf.all.rp_filter": value => "1"}
       #
       # log when rp_filter blocks packages
       sysctl::value { "net.ipv4.conf.all.log_martians": value => "1"}
       # eth0 = private network mit floating ip
       network_config { 'eth1':
         ipaddress => '192.168.2.102',
         method    => 'static',
         netmask   => '255.255.255.0',
         onboot    => 'true',
         options   => {
           'post-up' => [
             'ip route add 192.168.0.0/16 via 192.168.2.2 dev eth1',
           ],
           'pre-down' => [
             'ip route del 192.168.0.0/16 via 192.168.2.2 dev eth1',
           ],
         },
       }
     }
     node "ffhs-pc3" {
       # enable some basic security
       sysctl::value { "net.ipv4.conf.all.rp_filter": value => "1"}
       #
       # log when rp_filter blocks packages
       sysctl::value { "net.ipv4.conf.all.log_martians": value => "1"}
       # eth0 = private network mit floating ip
       network_config { 'eth1':
         ipaddress => '192.168.3.103',
         method    => 'static',
         netmask   => '255.255.255.0',
         onboot    => 'true',
         options   => {
           'post-up' => [
             'ip route add 192.168.0.0/16 via 192.168.3.3 dev eth1',
           ],
           'pre-down' => [
             'ip route del 192.168.0.0/16 via 192.168.3.3 dev eth1',
           ],
         },
       }
     }
